# Generated by Django 3.2 on 2021-08-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210828_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='community_id',
            field=models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
    ]
