# Generated by Django 3.2 on 2021-08-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_event_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='writer',
        ),
    ]
